spring.application.name=KafkaStub

# ????? Kafka ???????
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.auto-offset-reset=earliest

server.port=8080

# Topic
kafka.topic.posted-messages=postedmessages

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics

# Liveness, Readiness
management.endpoint.health.probes.enabled=true

# Details
management.endpoint.health.show-details=always

# App Info
management.info.env.enabled=true
info.app.name=Kafka HTTP Stub
info.app.version=1.0.0